// Code generated by github.com/bingcool/gen. DO NOT EDIT.
// Code generated by github.com/bingcool/gen. DO NOT EDIT.
// Code generated by github.com/bingcool/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBookQueue = "book_queue"

// BookQueue 预约队列任务表
type BookQueue struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	URL        string    `gorm:"column:url;not null;comment:预约url" json:"url"`                               // 预约url
	RelateID   int32     `gorm:"column:relate_id;not null;comment:关联的taskId" json:"relate_id"`               // 关联的taskId
	Type       int32     `gorm:"column:type;not null;comment:url类型，0-默认机器，1发到群里" json:"type"`                // url类型，0-默认机器，1发到群里
	Status     int32     `gorm:"column:status;comment:状态：0-待处理， 1-已处理" json:"status"`                        // 状态：0-待处理， 1-已处理
	CreatedAt  time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt  time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	CreateTime int32     `gorm:"column:create_time;comment:记录生成时间戳" json:"create_time"`                      // 记录生成时间戳
}

// TableName BookQueue's table name
func (*BookQueue) TableName() string {
	return TableNameBookQueue
}
