// Code generated by github.com/bingcool/gen. DO NOT EDIT.
// Code generated by github.com/bingcool/gen. DO NOT EDIT.
// Code generated by github.com/bingcool/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTaskQueue = "task_queue"

// TaskQueue 排队队列任务表
type TaskQueue struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	URL        string    `gorm:"column:url;not null;comment:队列url" json:"url"`                                    // 队列url
	QueueCode  string    `gorm:"column:queue_code;not null;comment:队列查询码" json:"queue_code"`                      // 队列查询码
	Status     int32     `gorm:"column:status;comment:状态：0-待处理，1-处理中, 2-处理完成, 3-异常的(过期，关闭网页等)" json:"status"`     // 状态：0-待处理，1-处理中, 2-处理完成, 3-异常的(过期，关闭网页等)
	Status1    int32     `gorm:"column:status_1;comment:状态：0-待处理，1-处理中, 2-处理完成, 3-异常的(过期，关闭网页等)" json:"status_1"` // 状态：0-待处理，1-处理中, 2-处理完成, 3-异常的(过期，关闭网页等)
	CreatedAt  time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`      // 创建时间
	UpdatedAt  time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`      // 更新时间
	CreateTime int32     `gorm:"column:create_time;not null" json:"create_time"`
}

// TableName TaskQueue's table name
func (*TaskQueue) TableName() string {
	return TableNameTaskQueue
}
