// Code generated by github.com/bingcool/gen. DO NOT EDIT.
// Code generated by github.com/bingcool/gen. DO NOT EDIT.
// Code generated by github.com/bingcool/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTblUser = "tbl_users"

// TblUser 用户表
type TblUser struct {
	UserID     int32     `gorm:"column:user_id;primaryKey;autoIncrement:true;comment:用户id" json:"user_id"`            // 用户id
	UserName   string    `gorm:"column:user_name;not null;comment:用户名称" json:"user_name"`                             // 用户名称
	Sex        bool      `gorm:"column:sex;not null;comment:用户性别，0-男，1-女" json:"sex"`                                 // 用户性别，0-男，1-女
	Birthday   time.Time `gorm:"column:birthday;comment:出生年月" json:"birthday"`                                        // 出生年月
	Phone      string    `gorm:"column:phone;not null;comment:手机号" json:"phone"`                                      // 手机号
	ExtandJSON string    `gorm:"column:extand_json;comment:扩展数据" json:"extand_json"`                                  // 扩展数据
	GmtCreate  time.Time `gorm:"column:gmt_create;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"gmt_create"` // 创建时间
	GmtModify  time.Time `gorm:"column:gmt_modify;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"gmt_modify"` // 更新时间
}

// TableName TblUser's table name
func (*TblUser) TableName() string {
	return TableNameTblUser
}
