// Code generated by github.com/bingcool/gen. DO NOT EDIT.
// Code generated by github.com/bingcool/gen. DO NOT EDIT.
// Code generated by github.com/bingcool/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTblOrder = "tbl_order"

// TblOrder 订单表
type TblOrder struct {
	OrderID           int64          `gorm:"column:order_id;primaryKey;comment:订单id" json:"order_id"`                             // 订单id
	UserID            int32          `gorm:"column:user_id;not null;comment:下单用户id" json:"user_id"`                               // 下单用户id
	ReceiverUserName  string         `gorm:"column:receiver_user_name;not null;comment:收货人" json:"receiver_user_name"`            // 收货人
	ReceiverUserPhone string         `gorm:"column:receiver_user_phone;not null;comment:收货人手机号" json:"receiver_user_phone"`       // 收货人手机号
	OrderAmount       float64        `gorm:"column:order_amount;not null;default:0.000000;comment:订单金额" json:"order_amount"`      // 订单金额
	OrderProductIds   string         `gorm:"column:order_product_ids;not null;comment:订单产品id" json:"order_product_ids"`           // 订单产品id
	OrderStatus       int32          `gorm:"column:order_status;not null;comment:订单状态" json:"order_status"`                       // 订单状态
	Address           string         `gorm:"column:address;not null;comment:物流地址" json:"address"`                                 // 物流地址
	Remark            string         `gorm:"column:remark;not null;comment:评论" json:"remark"`                                     // 评论
	ExpendData        string         `gorm:"column:expend_data;comment:数据" json:"expend_data"`                                    // 数据
	JSONData          string         `gorm:"column:json_data;comment:扩展数据" json:"json_data"`                                      // 扩展数据
	GmtCreate         time.Time      `gorm:"column:gmt_create;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"gmt_create"` // 创建时间
	GmtModify         time.Time      `gorm:"column:gmt_modify;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"gmt_modify"` // 更新时间
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                    // 删除时间
}

// TableName TblOrder's table name
func (*TblOrder) TableName() string {
	return TableNameTblOrder
}
