// Code generated by github.com/bingcool/gen. DO NOT EDIT.
// Code generated by github.com/bingcool/gen. DO NOT EDIT.
// Code generated by github.com/bingcool/gen. DO NOT EDIT.

package entity

import (
	"fmt"
	"goTest/domain/dao/model"
	"gorm.io/gorm"
)

const TableNameTblUser = "tbl_users"

// TblUser 用户表
type TblUser struct {
	model.TblUser
}

// TableName TblUser's table name
func (*TblUser) TableName() string {
	return TableNameTblUser
}

func (user *TblUser) AfterFind(tx *gorm.DB) (err error) {
	fmt.Println("AfterFind")
	return
}

func (user *TblUser) BeforeSave(tx *gorm.DB) (err error) {
	fmt.Println("BeforeSave")
	return
}

func (user *TblUser) AfterCreate(tx *gorm.DB) (err error) {
	fmt.Println("AfterCreate")
	return
}
